<a href="https://colab.research.google.com/github/aadithya-vimal/SamsungInnovationCampus/blob/main/pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operations in Pandas

In [242]:
exam_data = {
    'Physics' : [67,98,72,45],
    'Chemistry' : [67,98,72,45],
    'Math' : [67,98,72,45],
    'Bio' : [67,98,72,45]
}
print(f"Created 'exam_data' dictionary: \n {exam_data}")

Created 'exam_data' dictionary:
 {'Physics': [67, 98, 72, 45], 'Chemistry': [67, 98, 72, 45], 'Math': [67, 98, 72, 45], 'Bio': [67, 98, 72, 45]}

In [243]:
#Creating dataframe
import pandas as pd
df = pd.DataFrame(exam_data, index = ['S1', 'S2', 'S3', 'S4'])
print(f"\n Created 'df' dataframe: \n\n {df}")
print("\nTable format:\n")
display(df)

 Created 'df' dataframe:

     Physics  Chemistry  Math  Bio
S1       67         67    67   67
S2       98         98    98   98
S3       72         72    72   72
S4       45         45    45   45

Table format:

    Physics  Chemistry  Math  Bio
S1       67         67    67   67
S2       98         98    98   98
S3       72         72    72   72
S4       45         45    45   45

In [244]:
#Deleting/dropping a row
df2 = df3 = df.copy()
df2.drop('S1', inplace=True)
df3.drop('Math', inplace=True, axis=1)
print(f"Original dataframe: \n {df}")
print(f"\nNew dataframe with deleted row: \n {df2}")
print(f"\nNew dataframe with deleted column: \n {df3}")

Original dataframe:
     Physics  Chemistry  Math  Bio
S1       67         67    67   67
S2       98         98    98   98
S3       72         72    72   72
S4       45         45    45   45

New dataframe with deleted row:
     Physics  Chemistry  Bio
S2       98         98   98
S3       72         72   72
S4       45         45   45

New dataframe with deleted column:
     Physics  Chemistry  Bio
S2       98         98   98
S3       72         72   72
S4       45         45   45

In [245]:
#Accessing values of single row
df4 = df.copy()
display(df.loc['S2'])
display(df.iloc[2])

Physics      98
Chemistry    98
Math         98
Bio          98
Name: S2, dtype: int64

Physics      72
Chemistry    72
Math         72
Bio          72
Name: S3, dtype: int64

In [246]:
#Extracting filtered rows
df5 = df.copy()
df6 = df.copy()
display(df5.iloc[[0,2]])
display(df6.loc[: , 'Math'])

    Physics  Chemistry  Math  Bio
S1       67         67    67   67
S3       72         72    72   72

S1    67
S2    98
S3    72
S4    45
Name: Math, dtype: int64

In [247]:
#Renaming index
df7 = df.copy()
df7.index = ['Asha', 'Bala', 'Charan', 'Darsh']
display(df7)

        Physics  Chemistry  Math  Bio
Asha         67         67    67   67
Bala         98         98    98   98
Charan       72         72    72   72
Darsh        45         45    45   45

In [248]:
#Accessing real time data
df7.iloc[0, :3]

Physics      67
Chemistry    67
Math         67
Name: Asha, dtype: int64

In [249]:
df8 = df7.copy()
# Create a new row with the sum of each column
df8.loc['Total'] = df8.sum()

display(df8)

        Physics  Chemistry  Math  Bio
Asha         67         67    67   67
Bala         98         98    98   98
Charan       72         72    72   72
Darsh        45         45    45   45
Total       282        282   282  282

In [250]:
df9 = df.copy()
df9.reset_index(inplace=True)
display(df9)
df9.rename(columns={'index' : 'Names'}, inplace = True)
display(df9)

  index  Physics  Chemistry  Math  Bio
0    S1       67         67    67   67
1    S2       98         98    98   98
2    S3       72         72    72   72
3    S4       45         45    45   45

  Names  Physics  Chemistry  Math  Bio
0    S1       67         67    67   67
1    S2       98         98    98   98
2    S3       72         72    72   72
3    S4       45         45    45   45

In [251]:
df10 = df7.copy()
df10.loc['Eevee'] = {
    'Physics' : 67,
    'Chemistry' : 98,
    'Math' : 72,
    'Bio' : 45
}
df10.loc['Total'] = df10.sum()
df10.reset_index(inplace=True)
df10.rename(columns={'index' : 'Names'}, inplace = True)
display(df10)

    Names  Physics  Chemistry  Math  Bio
0    Asha       67         67    67   67
1    Bala       98         98    98   98
2  Charan       72         72    72   72
3   Darsh       45         45    45   45
4   Eevee       67         98    72   45
5   Total      349        380   354  327

In [252]:
df11 = df7.copy()
df11.loc['Asha','Physics'] =100
display(df11)

        Physics  Chemistry  Math  Bio
Asha        100         67    67   67
Bala         98         98    98   98
Charan       72         72    72   72
Darsh        45         45    45   45

In [253]:
df12=df7.copy()
t_data = df12.T
display(t_data)
display(df12)

           Asha  Bala  Charan  Darsh
Physics      67    98      72     45
Chemistry    67    98      72     45
Math         67    98      72     45
Bio          67    98      72     45

        Physics  Chemistry  Math  Bio
Asha         67         67    67   67
Bala         98         98    98   98
Charan       72         72    72   72
Darsh        45         45    45   45

In [254]:
df13=df10.copy()
sorted_data_p=df13.sort_values(by='Physics', ascending=False)
sorted_data_n=df13.sort_values(by='Names', ascending=False)
print(f"Sorted data: (Physics)\n\n {sorted_data_p}")
print(f"\nSorted data: (Names)\n\n {sorted_data_n}")

Sorted data: (Physics)

     Names  Physics  Chemistry  Math  Bio
5   Total      349        380   354  327
1    Bala       98         98    98   98
2  Charan       72         72    72   72
0    Asha       67         67    67   67
4   Eevee       67         98    72   45
3   Darsh       45         45    45   45

Sorted data: (Names)

     Names  Physics  Chemistry  Math  Bio
5   Total      349        380   354  327
4   Eevee       67         98    72   45
3   Darsh       45         45    45   45
2  Charan       72         72    72   72
1    Bala       98         98    98   98
0    Asha       67         67    67   67

In [255]:
df14=df10.copy()
# Select the row where 'Names' is 'Asha'
asha_data = df14[df14['Names'] == 'Asha']

# Select the numeric columns from asha_data
numeric_cols = ['Physics', 'Chemistry', 'Math', 'Bio']
asha_numeric_df = asha_data[numeric_cols]

sum_val = asha_numeric_df.sum(axis=1).iloc[0]
prod_val = asha_numeric_df.prod(axis=1).iloc[0]
diff_val = (asha_numeric_df['Physics'] - asha_numeric_df['Chemistry'] - asha_numeric_df['Math'] - asha_numeric_df['Bio']).iloc[0]
fract = asha_numeric_df / 100

# Print the results directly
print(f"Sum: {sum_val}")
print(f"Product: {prod_val}")
print(f"Difference: {diff_val}")
print(f"Fraction:\n{fract.to_string(index=False)}")

Sum: 268
Product: 20151121
Difference: -134
Fraction:
 Physics  Chemistry  Math  Bio
    0.67       0.67  0.67 0.67

In [257]:
import seaborn as sns
data = sns.load_dataset('titanic')
tdf=pd.DataFrame(data)
display(tdf)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [259]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [266]:
tdf.shape

(891, 15)

In [261]:
tdf.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [265]:
tdf1 = tdf.copy()
display(tdf1.loc[:, ['age', 'fare']])
display(tdf1.iloc[:, [3,6]])

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [269]:
tdf2 = tdf.copy()
#Must be only numerical data, categorical data is unsupported
tdf2=tdf2.iloc[:, [3,6]]
display(tdf2)
sum = tdf2+10
sum.head()

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [275]:
#Merging data
a_values = {'Name':['A', 'B', 'C', 'D'], 'Gender': ['M', 'F', 'M', 'F'], 'Age': [20,24,21,24]}
b_values = {'Name':['E', 'A', 'G', 'B'], 'Position': ['Assistant', 'Leader', 'Sweeper', 'Security'], 'Salary':[564654,98782,2132132,89896]}
df_a = pd.DataFrame(a_values)
df_b = pd.DataFrame(b_values)
pd.merge(df_a,df_b,on='Name',how='outer')

  Name Gender   Age   Position     Salary
0    A      M  20.0     Leader    98782.0
1    B      F  24.0   Security    89896.0
2    C      M  21.0        NaN        NaN
3    D      F  24.0        NaN        NaN
4    E    NaN   NaN  Assistant   564654.0
5    G    NaN   NaN    Sweeper  2132132.0

In [280]:
#Concatenating data
pd.concat([df_a,df_b],axis=1)

  Name Gender  Age Name   Position   Salary
0    A      M   20    E  Assistant   564654
1    B      F   24    A     Leader    98782
2    C      M   21    G    Sweeper  2132132
3    D      F   24    B   Security    89896

In [281]:
tdf3 = tdf.copy()
tdf3.sort_values(['age', 'fare'])

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
527,0,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,no,True
557,0,1,male,NaN,0,0,227.5250,C,First,man,True,NaN,Cherbourg,no,True

In [300]:
tdf4=tdf.copy()
tdf4_analyzed=pd.pivot_table(tdf4, index=['who'], columns='survived', values='age', aggfunc='count')
tdf4_analyzed['Total']=tdf4_analyzed.sum(axis=1)
tdf4_analyzed.loc['Total']=tdf4_analyzed.sum(axis=0)
display(tdf4_analyzed)

survived    0    1  Total
who
child      34   49     83
man       341   72    413
woman      49  169    218
Total     424  290    714

In [304]:
tdf5=tdf.copy()
display(tdf5.groupby(['who', 'survived'])['pclass'].mean())
print(f"Number of null values in age column: {tdf5['age'].isnull().sum()}")

who    survived
child  0           2.941176
       1           2.408163
man    0           2.454343
       1           1.954545
woman  0           2.848485
       1           1.839024
Name: pclass, dtype: float64

Number of null values in age column: 177