<a href="https://colab.research.google.com/github/aadithya-vimal/SamsungInnovationCampus/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing in Python

## Handling missing data

In [109]:
#Loading the dataset
import seaborn as sns
import pandas as pd

data = sns.load_dataset('titanic')
df = pd.DataFrame(data)

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [110]:
df.shape

(891, 15)

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [112]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [113]:
df.notnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True
887,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
888,True,True,True,False,True,True,True,True,True,True,True,False,True,True,True
889,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
890,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True

In [114]:
#Total number of NaN in each column
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [115]:
df1 = df.copy()
df1.dropna(axis=1, thresh=500, inplace=True)
df1.shape

(891, 14)

In [116]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

In [117]:
df1.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [118]:
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [119]:
display(df1.isnull().sum())
display(df1.shape)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

(891, 14)

In [120]:
df2 = df.copy()
df2.dropna(axis=1, thresh=500, inplace=True)
df2.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

In [121]:
df3 = df.copy()
df3.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [122]:
df3.dropna(subset=['age'], axis=0, inplace=True)
display(df2.isnull().sum())
display(df.shape)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
embark_town      2
alive            0
alone            0
dtype: int64

(891, 15)

In [123]:
df4 = df.copy()
df4['age'] = df4['age'].fillna(0)
deck_mode = df4['deck'].mode()[0]
df4['deck'] = df4['deck'].fillna(deck_mode)

# Check the results
print(df4.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
deck           0
embark_town    2
alive          0
alone          0
dtype: int64

In [124]:
df5 = df.copy()
df5['age'] = df5['age'].fillna(df5['age'].median())
deck_mode = df5['deck'].mode()[0]
df5['deck'] = df5['deck'].fillna(deck_mode)

print(df5.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
deck           0
embark_town    2
alive          0
alone          0
dtype: int64

In [125]:
df6 = df.copy()
mode = df6['age'].mode()[0]
df6['age'] = df6['age'].fillna(mode)
deck_mode = df6['deck'].mode()[0]
df6['deck'] = df6['deck'].fillna(deck_mode)
print(df6.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
deck           0
embark_town    2
alive          0
alone          0
dtype: int64

## Handling duplicate values

In [126]:
df7 = df.copy()
df7.duplicated().sum()

np.int64(107)

In [127]:
df7.drop_duplicates(inplace=True)
df7.duplicated().sum()

np.int64(0)

## Outlier handling

In [128]:
from scipy.stats import zscore
df8 = df4.copy()
df8['Z_Score'] = zscore(df8['age'])
outliers = df8.loc[df8['Z_Score']>=3]
print(f"DF with Z Scores: \n {df8}")
print(f"Outliers: \n {outliers}")

DF with Z Scores:
      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   0.0      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone   Z_Score
0      man        True    C  Southampton    no  False -0.102313
1    woman       False    C    Cherbourg   yes  False  0.807492
2    woman       False    C  Southampton   yes   True  0.125138
3    woman       False    C  Southampton   yes  False  0.636903
4      man        True    C  Southampton    no   True  0.636903
..     ...         ...  ...          ...   ...    ...       ...
886    man        True    C  Southampton    no   True  0.182001
887  woman       False    B  Southampton   yes   True -0.272901
888  woman       False    C  Southampton    no  False -1.353294
889    man        True    C    Cherbourg   yes   True  0.125138
890    man        True    C   Queenstown    no   True  0.466315

[891 rows x 16 columns]
Outliers:
      survived  pclass   sex   age  sibsp  parch  fare embarked  class  who  \
630         1       1  male  80.0      0      0  30.0        S  First  man

     adult_male deck  embark_town alive  alone   Z_Score
630        True    A  Southampton   yes   True  3.195728

In [129]:
df9 = df4.copy()
Q1 = df9['age'].quantile(0.25)
Q3 = df9['age'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df9['age'] < lower_bound) | (df9['age'] > upper_bound)]
print(outliers)
df9_no_outliers = df9[(df9['age'] >= lower_bound) & (df9['age'] <= upper_bound)]
print(df9_no_outliers)

     survived  pclass   sex   age  sibsp  parch  fare embarked  class  who  \
630         1       1  male  80.0      0      0  30.0        S  First  man

     adult_male deck  embark_town alive  alone
630        True    A  Southampton   yes   True
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   0.0      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True    C  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False    C  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True    C  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True    C  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False    C  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True    C   Queenstown    no   True

[890 rows x 15 columns]

In [130]:
data2 = pd.read_csv('data_sales.csv')
df10 = pd.DataFrame(data2)
df10.head()

        Date   Region     Item  Unit Price  Units
0  04-Jul-14     East  Pen Set        4.99     62
1  12-Jul-14     East   Binder        1.99     29
2  21-Jul-14  Central  Pen Set       12.49     55
3  29-Jul-14     East   Binder       19.99     81
4  07-Aug-14  Central  Pen Set       23.95     42

In [131]:
df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        43 non-null     object
 1   Region      43 non-null     object
 2   Item        43 non-null     object
 3   Unit Price  43 non-null     float64
 4   Units       43 non-null     int64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.8+ KB

In [132]:
df10['Month'] = pd.to_datetime(df10['Date']).dt.month
df10['Quarter'] = pd.to_datetime(df10['Date']).dt.quarter
df10.head()

/tmp/ipykernel_5207/986239571.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df10['Month'] = pd.to_datetime(df10['Date']).dt.month
/tmp/ipykernel_5207/986239571.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df10['Quarter'] = pd.to_datetime(df10['Date']).dt.quarter

        Date   Region     Item  Unit Price  Units  Month  Quarter
0  04-Jul-14     East  Pen Set        4.99     62      7        3
1  12-Jul-14     East   Binder        1.99     29      7        3
2  21-Jul-14  Central  Pen Set       12.49     55      7        3
3  29-Jul-14     East   Binder       19.99     81      7        3
4  07-Aug-14  Central  Pen Set       23.95     42      8        3

In [133]:
df10['Revenue'] = df10['Unit Price']*df10['Units']
df10.head()

        Date   Region     Item  Unit Price  Units  Month  Quarter  Revenue
0  04-Jul-14     East  Pen Set        4.99     62      7        3   309.38
1  12-Jul-14     East   Binder        1.99     29      7        3    57.71
2  21-Jul-14  Central  Pen Set       12.49     55      7        3   686.95
3  29-Jul-14     East   Binder       19.99     81      7        3  1619.19
4  07-Aug-14  Central  Pen Set       23.95     42      8        3  1005.90

In [134]:
df10.groupby('Quarter')['Revenue'].sum()

Quarter
1    4203.29
2    3972.88
3    5344.89
4    6106.82
Name: Revenue, dtype: float64

In [135]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df10['EncodedRegion'] = le.fit_transform(df10['Region'])
df10

,Date,Region,Item,Unit Price,Units,Month,Quarter,Revenue,EncodedRegion
0,04-Jul-14,East,Pen Set,4.99,62,7,3,309.38,1
1,12-Jul-14,East,Binder,1.99,29,7,3,57.71,1
2,21-Jul-14,Central,Pen Set,12.49,55,7,3,686.95,0
3,29-Jul-14,East,Binder,19.99,81,7,3,1619.19,1
4,07-Aug-14,Central,Pen Set,23.95,42,8,3,1005.90,0
5,15-Aug-14,East,Pencil,4.99,35,8,3,174.65,1
6,24-Aug-14,West,Desk,275.00,3,8,3,825.00,2
7,01-Sep-14,Central,Desk,125.00,2,9,3,250.00,0
8,10-Sep-14,Central,Pencil,1.29,7,9,3,9.03,0
9,18-Sep-14,East,Pen Set,15.99,16,9,3,255.84,1
10,27-Sep-14,West,Pen,1.99,76,9,3,151.24,2
11,05-Oct-14,Central,Binder,8.99,28,10,4,251.72,0
12,14-Oct-14,West,Binder,19.99,57,10,4,1139.43,2
13,22-Oct-14,East,Pen,8.99,64,10,4,575.36,1
14,31-Oct-14,Central,Pencil,1.29,14,10,4,18.06,0
15,08-Nov-14,East,Pen,19.99,15,11,4,299.85,1
16,17-Nov-14,Central,Binder,4.99,11,11,4,54.89,0
17,25-Nov-14,Central,Pen Set,4.99,96,11,4,479.04,0
18,04-Dec-14,Central,Binder,19.99,94,12,4,1879.06,0
19,12-Dec-14,Central,Pencil,1.29,67,12,4,86.43,0
20,21-Dec-14,Central,Binder,4.99,28,12,4,139.72,0
21,29-Dec-14,East,Pen Set,15.99,74,12,4,1183.26,1
22,06-Jan-15,East,Pencil,1.99,95,1,1,189.05,1
23,15-Jan-15,Central,Binder,8.99,46,1,1,413.54,0
24,23-Jan-15,Central,Binder,19.99,50,1,1,999.50,0
25,01-Feb-15,Central,Binder,15.00,87,2,1,1305.00,0
26,09-Feb-15,Central,Pencil,4.99,36,2,1,179.64,0
27,18-Feb-15,East,Binder,4.99,4,2,1,19.96,1
28,26-Feb-15,Central,Pen,19.99,27,2,1,539.73,0
29,07-Mar-15,West,Binder,19.99,7,3,1,139.93,2
30,15-Mar-15,West,Pencil,2.99,56,3,1,167.44,2
31,24-Mar-15,Central,Pen Set,4.99,50,3,1,249.50,0
32,01-Apr-15,East,Binder,4.99,60,4,2,299.40,1
33,10-Apr-15,Central,Pencil,1.99,66,4,2,131.34,0
34,18-Apr-15,Central,Pencil,1.99,75,4,2,149.25,0
35,27-Apr-15,East,Pen,4.99,96,4,2,479.04,1
36,05-May-15,Central,Pencil,4.99,90,5,2,449.10,0
37,14-May-15,Central,Pencil,1.29,53,5,2,68.37,0
38,22-May-15,West,Pencil,1.99,32,5,2,63.68,2
39,31-May-15,Central,Binder,8.99,80,5,2,719.20,0
40,08-Jun-15,East,Binder,8.99,60,6,2,539.40,1
41,17-Jun-15,Central,Desk,125.00,5,6,2,625.00,0
42,25-Jun-15,Central,Pencil,4.99,90,6,2,449.10,0

In [138]:
from sys import prefix
df11 = pd.get_dummies(df10, columns=['Region'], prefix='Region')
df11

,Date,Item,Unit Price,Units,Month,Quarter,Revenue,EncodedRegion,Region_Central,Region_East,Region_West
0,04-Jul-14,Pen Set,4.99,62,7,3,309.38,1,False,True,False
1,12-Jul-14,Binder,1.99,29,7,3,57.71,1,False,True,False
2,21-Jul-14,Pen Set,12.49,55,7,3,686.95,0,True,False,False
3,29-Jul-14,Binder,19.99,81,7,3,1619.19,1,False,True,False
4,07-Aug-14,Pen Set,23.95,42,8,3,1005.90,0,True,False,False
5,15-Aug-14,Pencil,4.99,35,8,3,174.65,1,False,True,False
6,24-Aug-14,Desk,275.00,3,8,3,825.00,2,False,False,True
7,01-Sep-14,Desk,125.00,2,9,3,250.00,0,True,False,False
8,10-Sep-14,Pencil,1.29,7,9,3,9.03,0,True,False,False
9,18-Sep-14,Pen Set,15.99,16,9,3,255.84,1,False,True,False
10,27-Sep-14,Pen,1.99,76,9,3,151.24,2,False,False,True
11,05-Oct-14,Binder,8.99,28,10,4,251.72,0,True,False,False
12,14-Oct-14,Binder,19.99,57,10,4,1139.43,2,False,False,True
13,22-Oct-14,Pen,8.99,64,10,4,575.36,1,False,True,False
14,31-Oct-14,Pencil,1.29,14,10,4,18.06,0,True,False,False
15,08-Nov-14,Pen,19.99,15,11,4,299.85,1,False,True,False
16,17-Nov-14,Binder,4.99,11,11,4,54.89,0,True,False,False
17,25-Nov-14,Pen Set,4.99,96,11,4,479.04,0,True,False,False
18,04-Dec-14,Binder,19.99,94,12,4,1879.06,0,True,False,False
19,12-Dec-14,Pencil,1.29,67,12,4,86.43,0,True,False,False
20,21-Dec-14,Binder,4.99,28,12,4,139.72,0,True,False,False
21,29-Dec-14,Pen Set,15.99,74,12,4,1183.26,1,False,True,False
22,06-Jan-15,Pencil,1.99,95,1,1,189.05,1,False,True,False
23,15-Jan-15,Binder,8.99,46,1,1,413.54,0,True,False,False
24,23-Jan-15,Binder,19.99,50,1,1,999.50,0,True,False,False
25,01-Feb-15,Binder,15.00,87,2,1,1305.00,0,True,False,False
26,09-Feb-15,Pencil,4.99,36,2,1,179.64,0,True,False,False
27,18-Feb-15,Binder,4.99,4,2,1,19.96,1,False,True,False
28,26-Feb-15,Pen,19.99,27,2,1,539.73,0,True,False,False
29,07-Mar-15,Binder,19.99,7,3,1,139.93,2,False,False,True
30,15-Mar-15,Pencil,2.99,56,3,1,167.44,2,False,False,True
31,24-Mar-15,Pen Set,4.99,50,3,1,249.50,0,True,False,False
32,01-Apr-15,Binder,4.99,60,4,2,299.40,1,False,True,False
33,10-Apr-15,Pencil,1.99,66,4,2,131.34,0,True,False,False
34,18-Apr-15,Pencil,1.99,75,4,2,149.25,0,True,False,False
35,27-Apr-15,Pen,4.99,96,4,2,479.04,1,False,True,False
36,05-May-15,Pencil,4.99,90,5,2,449.10,0,True,False,False
37,14-May-15,Pencil,1.29,53,5,2,68.37,0,True,False,False
38,22-May-15,Pencil,1.99,32,5,2,63.68,2,False,False,True
39,31-May-15,Binder,8.99,80,5,2,719.20,0,True,False,False
40,08-Jun-15,Binder,8.99,60,6,2,539.40,1,False,True,False
41,17-Jun-15,Desk,125.00,5,6,2,625.00,0,True,False,False
42,25-Jun-15,Pencil,4.99,90,6,2,449.10,0,True,False,False

In [142]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df12 = df11.copy()
df12['Scaled Price(MinMax)']=scaler.fit_transform(df12[['Unit Price']])
df12

,Date,Item,Unit Price,Units,Month,Quarter,Revenue,EncodedRegion,Region_Central,Region_East,Region_West,Scaled Price(MinMax)
0,04-Jul-14,Pen Set,4.99,62,7,3,309.38,1,False,True,False,0.013518
1,12-Jul-14,Binder,1.99,29,7,3,57.71,1,False,True,False,0.002557
2,21-Jul-14,Pen Set,12.49,55,7,3,686.95,0,True,False,False,0.040919
3,29-Jul-14,Binder,19.99,81,7,3,1619.19,1,False,True,False,0.068320
4,07-Aug-14,Pen Set,23.95,42,8,3,1005.90,0,True,False,False,0.082788
5,15-Aug-14,Pencil,4.99,35,8,3,174.65,1,False,True,False,0.013518
6,24-Aug-14,Desk,275.00,3,8,3,825.00,2,False,False,True,1.000000
7,01-Sep-14,Desk,125.00,2,9,3,250.00,0,True,False,False,0.451975
8,10-Sep-14,Pencil,1.29,7,9,3,9.03,0,True,False,False,0.000000
9,18-Sep-14,Pen Set,15.99,16,9,3,255.84,1,False,True,False,0.053706
10,27-Sep-14,Pen,1.99,76,9,3,151.24,2,False,False,True,0.002557
11,05-Oct-14,Binder,8.99,28,10,4,251.72,0,True,False,False,0.028132
12,14-Oct-14,Binder,19.99,57,10,4,1139.43,2,False,False,True,0.068320
13,22-Oct-14,Pen,8.99,64,10,4,575.36,1,False,True,False,0.028132
14,31-Oct-14,Pencil,1.29,14,10,4,18.06,0,True,False,False,0.000000
15,08-Nov-14,Pen,19.99,15,11,4,299.85,1,False,True,False,0.068320
16,17-Nov-14,Binder,4.99,11,11,4,54.89,0,True,False,False,0.013518
17,25-Nov-14,Pen Set,4.99,96,11,4,479.04,0,True,False,False,0.013518
18,04-Dec-14,Binder,19.99,94,12,4,1879.06,0,True,False,False,0.068320
19,12-Dec-14,Pencil,1.29,67,12,4,86.43,0,True,False,False,0.000000
20,21-Dec-14,Binder,4.99,28,12,4,139.72,0,True,False,False,0.013518
21,29-Dec-14,Pen Set,15.99,74,12,4,1183.26,1,False,True,False,0.053706
22,06-Jan-15,Pencil,1.99,95,1,1,189.05,1,False,True,False,0.002557
23,15-Jan-15,Binder,8.99,46,1,1,413.54,0,True,False,False,0.028132
24,23-Jan-15,Binder,19.99,50,1,1,999.50,0,True,False,False,0.068320
25,01-Feb-15,Binder,15.00,87,2,1,1305.00,0,True,False,False,0.050090
26,09-Feb-15,Pencil,4.99,36,2,1,179.64,0,True,False,False,0.013518
27,18-Feb-15,Binder,4.99,4,2,1,19.96,1,False,True,False,0.013518
28,26-Feb-15,Pen,19.99,27,2,1,539.73,0,True,False,False,0.068320
29,07-Mar-15,Binder,19.99,7,3,1,139.93,2,False,False,True,0.068320
30,15-Mar-15,Pencil,2.99,56,3,1,167.44,2,False,False,True,0.006211
31,24-Mar-15,Pen Set,4.99,50,3,1,249.50,0,True,False,False,0.013518
32,01-Apr-15,Binder,4.99,60,4,2,299.40,1,False,True,False,0.013518
33,10-Apr-15,Pencil,1.99,66,4,2,131.34,0,True,False,False,0.002557
34,18-Apr-15,Pencil,1.99,75,4,2,149.25,0,True,False,False,0.002557
35,27-Apr-15,Pen,4.99,96,4,2,479.04,1,False,True,False,0.013518
36,05-May-15,Pencil,4.99,90,5,2,449.10,0,True,False,False,0.013518
37,14-May-15,Pencil,1.29,53,5,2,68.37,0,True,False,False,0.000000
38,22-May-15,Pencil,1.99,32,5,2,63.68,2,False,False,True,0.002557
39,31-May-15,Binder,8.99,80,5,2,719.20,0,True,False,False,0.028132
40,08-Jun-15,Binder,8.99,60,6,2,539.40,1,False,True,False,0.028132
41,17-Jun-15,Desk,125.00,5,6,2,625.00,0,True,False,False,0.451975
42,25-Jun-15,Pencil,4.99,90,6,2,449.10,0,True,False,False,0.013518

In [143]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df13 = df12.copy()
df13['Scaled Price(Standard)']=scaler.fit_transform(df12[['Unit Price']])
df13

,Date,Item,Unit Price,Units,Month,Quarter,Revenue,EncodedRegion,Region_Central,Region_East,Region_West,Scaled Price(MinMax),Scaled Price(Standard)
0,04-Jul-14,Pen Set,4.99,62,7,3,309.38,1,False,True,False,0.013518,-0.327381
1,12-Jul-14,Binder,1.99,29,7,3,57.71,1,False,True,False,0.002557,-0.391495
2,21-Jul-14,Pen Set,12.49,55,7,3,686.95,0,True,False,False,0.040919,-0.167095
3,29-Jul-14,Binder,19.99,81,7,3,1619.19,1,False,True,False,0.068320,-0.006809
4,07-Aug-14,Pen Set,23.95,42,8,3,1005.90,0,True,False,False,0.082788,0.077822
5,15-Aug-14,Pencil,4.99,35,8,3,174.65,1,False,True,False,0.013518,-0.327381
6,24-Aug-14,Desk,275.00,3,8,3,825.00,2,False,False,True,1.000000,5.443129
7,01-Sep-14,Desk,125.00,2,9,3,250.00,0,True,False,False,0.451975,2.237409
8,10-Sep-14,Pencil,1.29,7,9,3,9.03,0,True,False,False,0.000000,-0.406456
9,18-Sep-14,Pen Set,15.99,16,9,3,255.84,1,False,True,False,0.053706,-0.092295
10,27-Sep-14,Pen,1.99,76,9,3,151.24,2,False,False,True,0.002557,-0.391495
11,05-Oct-14,Binder,8.99,28,10,4,251.72,0,True,False,False,0.028132,-0.241895
12,14-Oct-14,Binder,19.99,57,10,4,1139.43,2,False,False,True,0.068320,-0.006809
13,22-Oct-14,Pen,8.99,64,10,4,575.36,1,False,True,False,0.028132,-0.241895
14,31-Oct-14,Pencil,1.29,14,10,4,18.06,0,True,False,False,0.000000,-0.406456
15,08-Nov-14,Pen,19.99,15,11,4,299.85,1,False,True,False,0.068320,-0.006809
16,17-Nov-14,Binder,4.99,11,11,4,54.89,0,True,False,False,0.013518,-0.327381
17,25-Nov-14,Pen Set,4.99,96,11,4,479.04,0,True,False,False,0.013518,-0.327381
18,04-Dec-14,Binder,19.99,94,12,4,1879.06,0,True,False,False,0.068320,-0.006809
19,12-Dec-14,Pencil,1.29,67,12,4,86.43,0,True,False,False,0.000000,-0.406456
20,21-Dec-14,Binder,4.99,28,12,4,139.72,0,True,False,False,0.013518,-0.327381
21,29-Dec-14,Pen Set,15.99,74,12,4,1183.26,1,False,True,False,0.053706,-0.092295
22,06-Jan-15,Pencil,1.99,95,1,1,189.05,1,False,True,False,0.002557,-0.391495
23,15-Jan-15,Binder,8.99,46,1,1,413.54,0,True,False,False,0.028132,-0.241895
24,23-Jan-15,Binder,19.99,50,1,1,999.50,0,True,False,False,0.068320,-0.006809
25,01-Feb-15,Binder,15.00,87,2,1,1305.00,0,True,False,False,0.050090,-0.113453
26,09-Feb-15,Pencil,4.99,36,2,1,179.64,0,True,False,False,0.013518,-0.327381
27,18-Feb-15,Binder,4.99,4,2,1,19.96,1,False,True,False,0.013518,-0.327381
28,26-Feb-15,Pen,19.99,27,2,1,539.73,0,True,False,False,0.068320,-0.006809
29,07-Mar-15,Binder,19.99,7,3,1,139.93,2,False,False,True,0.068320,-0.006809
30,15-Mar-15,Pencil,2.99,56,3,1,167.44,2,False,False,True,0.006211,-0.370124
31,24-Mar-15,Pen Set,4.99,50,3,1,249.50,0,True,False,False,0.013518,-0.327381
32,01-Apr-15,Binder,4.99,60,4,2,299.40,1,False,True,False,0.013518,-0.327381
33,10-Apr-15,Pencil,1.99,66,4,2,131.34,0,True,False,False,0.002557,-0.391495
34,18-Apr-15,Pencil,1.99,75,4,2,149.25,0,True,False,False,0.002557,-0.391495
35,27-Apr-15,Pen,4.99,96,4,2,479.04,1,False,True,False,0.013518,-0.327381
36,05-May-15,Pencil,4.99,90,5,2,449.10,0,True,False,False,0.013518,-0.327381
37,14-May-15,Pencil,1.29,53,5,2,68.37,0,True,False,False,0.000000,-0.406456
38,22-May-15,Pencil,1.99,32,5,2,63.68,2,False,False,True,0.002557,-0.391495
39,31-May-15,Binder,8.99,80,5,2,719.20,0,True,False,False,0.028132,-0.241895
40,08-Jun-15,Binder,8.99,60,6,2,539.40,1,False,True,False,0.028132,-0.241895
41,17-Jun-15,Desk,125.00,5,6,2,625.00,0,True,False,False,0.451975,2.237409
42,25-Jun-15,Pencil,4.99,90,6,2,449.10,0,True,False,False,0.013518,-0.327381

In [144]:
correlation = df4[['age', 'fare']].corr(method='pearson')
print(correlation)

           age      fare
age   1.000000  0.135516
fare  0.135516  1.000000